


student_scores = [78, 65, 89, 86, 55, 91, 64, 89]

total_scores = sum(student_scores)
print(total_scores)

# OR

total_scores = 0
for score in student_scores:
    total_scores += score
    
print(total_scores)

print(max(student_scores))
print(min(student_scores))

max_score = 0
for score in student_scores:
  if score > max_score:
    max_score = score
print(max_score)


# For Loops with Range
# The range() function generates a sequence of numbers from 0 to n-1.

# Example: Loop with Range

for i in range(3):
    print(i)
    
# Output:

# 0
# 1
# 2
# The for loop iterates over the sequence of numbers generated by range(3) and prints each number.

# Example: Loop with Range

for i in range(1, 4):
    print(i)
    
# Output:

# 1
# 2
# 3

# Example: Loop with Range

for i in range(1, 10, 2):
    print(i)
    
# Output:

# 1
# 3
# 5
# 7
# 9
# The range() function can take up to three arguments: start, stop, and step.

# The start argument specifies the starting value of the sequence.
# The stop argument specifies the end value of the sequence (not included).
# The step argument specifies the increment value.

# In the example above, range(1, 10, 2) generates a sequence of numbers from 1 to 9 with a step of 2.

# Example: Loop with Range

for i in range(5, 0, -1):
    print(i)
    
# Output:

# 5
# 4
# 3
# 2
# 1
# The range() function can generate a sequence of numbers in reverse order by specifying a negative step value.


# Example: Loop with Range

for i in range(5, 0, -2):
    print(i)
    
# Output:

# 5
# 3
# 1
# The range() function can generate a sequence of numbers in reverse order with a negative step value.

# Example: Loop with Range

total = 0

for number in range(1, 101):
  total += number
print(total)

# Output:

# 5050
    
# Password Generator Project

import random

# The random.choice() function can be used to generate a random password.

print("Welcome to the PyPassword Generator!")

letters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
numbers = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
symbols = ["!", "#", "$", "%", "&", "(", ")", "*", "+"]

password_letters = int(input("How many letters would you like in your password?\n"))

password_symbols = int(input("How many symbols would you like?\n"))

password_numbers = int(input("How many numbers would you like?\n"))

password = ""

for char in range(1, password_letters + 1):
  password += random.choice(letters)
  
for char in range(1, password_symbols + 1):
  password += random.choice(symbols)
  
for char in range(1, password_numbers + 1):
    password += random.choice(numbers)
    
print(password)
    
    