# Loops in Python
# Loop prints out each item in the list one by one.
city_names = ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"]
for city in city_names:
    print(city)
    
# Output:
# New York
# Los Angeles
# Chicago
# Houston
# Phoenix
# The for loop iterates over each element in the list city_names and prints it.

for city in "New York":
    print(city)

for city in city_names:
  print(city + " is a city in the United States.")    
    
    
# Example: Looping Through a String  

# For Loop with Range

# The range() function generates a sequence of numbers from 0 to n-1.

# Example: Loop with Range

for i in range(3):
    print(i)
    
# Output:

# 0
# 1
# 2  
# The for loop iterates over the sequence of numbers generated by range(3) and prints each number.



    




